const std = @import("std");

pub fn build(b: *std.build.Builder) void {
    const target = b.standardTargetOptions(.{});
    const mode = b.standardReleaseOptions();

    const dump = b.option(bool, "dump", "Dump generated bytecode to stderr") orelse false;

    const options = b.addOptions();
    options.addOption(bool, "dump", dump);

    const exe = b.addExecutable("mar", "source/main.zig");
    exe.install();

    const run_cmd = exe.run();
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| run_cmd.addArgs(args);

    const exe_tests = b.addTest("source/main.zig");

    for (&[_]*std.build.LibExeObjStep{ exe, exe_tests }) |it| {
        it.setTarget(target);
        it.setBuildMode(mode);
        it.addOptions("build_options", options);
    }

    b.step("run", "Run the app").dependOn(&run_cmd.step);
    b.step("test", "Run unit tests").dependOn(&exe_tests.step);
}
